#!/bin/bash

if [ -z $1 ]; then
    echo "Usage..."
    exit
fi

if [ ! -e "$1.asm" ]; then
    echo "Not found."
    exit
fi

yasm -Worphan-labels -g dwarf2 -f elf64 $1.asm -l $1.lst
ld -g -o $1 $1.o